title: AhnMaph Blog
tagline: A passion and curiosity
description: Blog chia se kien thuc cong nghe, mobile va trai nghiem ca nhan.
url: "https://ahnmaph.github.io"
baseurl: ""

lang: vi-VN
timezone: Asia/Ho_Chi_Minh

github:
  username: AhnMaph

theme: jekyll-theme-chirpy

social:
  name: AhnMaph
  email: ""
  links:
    - https://github.com/AhnMaph

avatar: /assets/img/avatar.svg

paginate: 10

plugins:
  - jekyll-include-cache

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: false
      pin: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
