title: "Portfolio & Blog cua toi"
email: "phamthanhan157@gmail.com"
description: "Compassion is often birthed in the valley of despair."

remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
